# Generated by Django 5.2 on 2026-03-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='like', max_length=50),
            preserve_default=False,
        ),
    ]
