# Generated by Codex on 2026-05-14

from django.db import migrations, models


def create_default_collection_cards(apps, schema_editor):
    CollectionCard = apps.get_model("store", "CollectionCard")
    defaults = [
        {
            "title": "JUST LIKE THAT",
            "subtitle": "Inspired by timeless masterpieces. Iconic compositions interpreted with modern confidence and luxurious depth.",
            "button_text": "Collection I",
            "collection_type": "like",
            "ordering": 1,
        },
        {
            "title": "JUST LOVE THAT",
            "subtitle": "Original scents made to stand apart. Distinct personalities created for those who prefer legacy over imitation.",
            "button_text": "Collection II",
            "collection_type": "love",
            "ordering": 2,
        },
    ]
    for data in defaults:
        CollectionCard.objects.get_or_create(title=data["title"], defaults=data)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_product_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="collections/")),
                ("button_text", models.CharField(default="Explore Collection", max_length=80)),
                ("collection_type", models.CharField(choices=[("like", "Inspired Fragrances"), ("love", "Original Fragrances"), ("custom", "Custom URL")], default="like", max_length=20)),
                ("destination_url", models.CharField(blank=True, max_length=255)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("ordering", "id"),
            },
        ),
        migrations.RunPython(create_default_collection_cards, migrations.RunPython.noop),
    ]
