# Generated by Codex on 2026-05-15

from django.db import migrations, models
from django.utils import timezone


def update_100ml_prices(apps, schema_editor):
    Variant = apps.get_model("store", "Variant")
    Variant.objects.filter(size__iexact="100ml", price=1299).update(price=1699)


def restore_100ml_prices(apps, schema_editor):
    Variant = apps.get_model("store", "Variant")
    Variant.objects.filter(size__iexact="100ml", price=1699).update(price=1299)


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_collectioncard"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectioncard",
            name="accent_color",
            field=models.CharField(blank=True, help_text="Optional CSS color, for example #d8c5a6", max_length=20),
        ),
        migrations.AddField(
            model_name="collectioncard",
            name="accent_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("whatsapp_number", models.CharField(blank=True, help_text="Owner WhatsApp number in international format, for example +919876543210.", max_length=25)),
                ("whatsapp_message", models.CharField(default="Hello JLT Fragrances, I would like help choosing a perfume.", max_length=180)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="NoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="notes/")),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("ordering", "name"),
            },
        ),
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=25)),
                ("purpose", models.CharField(choices=[("signup", "Signup"), ("login", "Login")], max_length=12)),
                ("code_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("first_name", models.CharField(blank=True, max_length=75)),
                ("last_name", models.CharField(blank=True, max_length=75)),
                ("receive_offers", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["phone_number", "purpose", "created_at"], name="store_phone_phone_n_dfa237_idx")],
            },
        ),
        migrations.RunPython(update_100ml_prices, restore_100ml_prices),
    ]

