# Generated by Django 5.2 on 2026-05-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_settings_notes_phoneotp_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
